### ISSUE TITLE
Yahoo!ニュースのスクレイピングのサンプルコードについて

### ISSUE THREAD

**Issue by gkzz** [orangain/scraping-hands-on#1]
tutorialのYahoo!ニュースのスクレイピングのサンプルコードがanswer内で見当たらないのですが、ご確認お願いできますでしょうか。

―――――――――――――――――――引用―――――――――――――――――――――――――――――――――――――――――――――

Pythonクローリング&スクレイピング ハンズオン
このハンズオンでは、Yahoo!ニュースのトップニュースを題材として、Pythonによるスクレイピングを学びます。

サードパーティライブラリのRequestsとBeautiful Soupを使います。
（以下略）
https://github.com/orangain/scraping-hands-on/blob/master/tutorial.md

**Comment by orangain** [comment]
チュートリアルはPythonのインタラクティブシェルで「4. スクレイピングの実施」の`>>>`の部分のコードを入力していくことで完了するものなので、特に解答は用意しておりません。

`>>>`のコードを1つのスクリプトファイルにまとめれば、そのまま動かせると思います。

**Comment by gkzz** [comment]
お返事が遅くなり、大変申し訳ございません。
先ほどトライしたところ、実行できました！！

ご教授いただき、ありがとうございます！！

**Comment by orangain** [comment]
無事に実行できて良かったです 😄
